services:
  - docker:19.03.1-dind

before_script:
  - docker login $UDEVS_REGISTRY --username $UDEVS_REGISTRY_USER --password $UDEVS_REGISTRY_PASSWORD

stages:
  - build
  - deploy

build_image:
  stage: build
  script:
    - make build-image TAG=$CI_PIPELINE_IID REGISTRY=$UDEVS_REGISTRY
    - make push-image TAG=$CI_PIPELINE_IID REGISTRY=$UDEVS_REGISTRY
  only:
    - master

deploy_to_prod:
  stage: deploy
  script:
    - curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x ./kubectl && mkdir -p ~/.kube && mv ./kubectl ~/.kube && export PATH=$PATH:$HOME/.kube
    - cp $MUNO_KUBECONFIG ~/.kube/config
    - source .build_info
    - kubectl apply -f .kube/
    - kubectl set image deployment/$DEPLOYMENT $DEPLOYMENT=$UDEVS_REGISTRY/$APP:$CI_PIPELINE_IID
    - rm -rf ~/.kube
  only:
    - master
